# Generated by Django 3.2 on 2023-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sellingPrice', models.IntegerField()),
                ('purchasingPrice', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
